### PR TITLE
Added institute info in about section.

### LINKED ISSUE #13: Update About section
Just checked out the about section of blog(http://iiitv.github.io/about.html). The content in all the sections is currently filled with Lorem ipsum text. I think we need to add content to these sections.

### PR DESCRIPTION
**Pull request by nlok5923**
fixes : #13

### CODE REVIEW

**Comment by nlok5923** [comment]
@iiitv/project-maintainers sir please review this pull request and sorry for the typo in institute spelling in the newest commit message.

**Comment by akash1997** [comment]
Hi @nlok5923, thanks for taking the initiative to add the institute info in the about section. Can you also please go through and add the points in the institute's about page [here](http://iiitvadodara.ac.in/about.php). Also, I would also suggest you to remove the '-' in 'IIIT-V' and replace the newly formed part with the year our institute was established(2013).

**Comment by nlok5923** [comment]
@akash1997 sir please can you tell me where can i find the repo for institute about page .

**Comment by akash1997** [comment]
Just go through the page that I have mentioned in the previous message and add those details in the about section. I don't see why you need the repo for that.

**Comment by nlok5923** [comment]
@akash1997  sorry sir i misinterpreted it.

**Review by akash1997 — APPROVED** [review]

**Review by aashutoshrathi — APPROVED** [review]

**Pull request merged**
